"""All ORM models re-exported for migration auto-creation."""

from app.db import Base
from app.models.assets import MediaAsset, Scene
from app.models.avatar import AvatarOutputRow, AvatarProfileRow
from app.models.base import ContentStatus, can_transition
from app.models.brand import (
    Brand,
    BrandAsset,
    BrandDNARow,
    BrandEffectiveConfig,
    BrandOverride,
    BrandPreset,
)
from app.models.campaign import CampaignPlan, PlatformVariant, PublishingPlan
from app.models.capabilities import CapabilityPermission, ToolCallAudit
from app.models.collab import (
    PROJECT_TARGET_TYPES,
    Comment,
    ExportJob,
    ExportProfile,
    Notification,
    Project,
    ProjectArchive,
    ProjectMember,
    ProjectTarget,
    RetentionPolicy,
    Review,
    ReviewAssignment,
    ReviewDecision,
    RevisionRequest,
)
from app.models.community import (
    CommunityAction,
    CommunityInsight,
    CommunityOpportunity,
    CommunitySyncState,
    Conversation,
    SocialInteraction,
)
from app.models.content import (
    Campaign,
    ContentItem,
    Opportunity,
    PostMetric,
    PublishedPost,
    PublishingJob,
    QualityCheck,
    ScheduleEntry,
    TrendSource,
    Video,
    VideoVariant,
)
from app.models.creative import CreativeCommandRow
from app.models.dubbing import DubbingPlanRow

# Work 16.1 §1: ``experiment`` was registered on ``Base.metadata`` only as a side
# effect of importing ``app.api.v1.experiments`` or
# ``app.engine.performance.experiments``. That made table registration depend on
# import order -- the same class of defect ``run_migrations`` had, where schema
# correctness depended on whether something unrelated had been imported first.
# It also meant the Work 16.1 parity check classified ``experiments`` as a
# "migration-only" table in some runs and an ORM table in others.
from app.models.experiment import Experiment
from app.models.identity import (
    ApiCredential,
    AuditLog,
    RefreshToken,
    SocialAccount,
    User,
    WebhookSubscription,
    Workspace,
    WorkspaceApiKey,
    WorkspaceMember,
)
from app.models.integrations import TelegramLink
from app.models.intelligence import BrowserRun, DecisionRecordRow, EvidenceRecord
from app.models.knowledge import (
    KnowledgeEdge,
    KnowledgeEvidence,
    KnowledgeMemory,
    KnowledgeNode,
    SourceConnector,
    SourceDocument,
)
from app.models.lipsync import LipSyncJob
from app.models.localization import GlossaryTerm, LocalizationQCReport, LocalizedContent
from app.models.longform import LongFormChapter, LongFormProject
from app.models.media_intel import (
    ActiveSpeakerMap,
    AudioTimeMap,
    DiarizationSegment,
    EditProposal,
    FaceTrack,
    FaceTrackSample,
    IntelQCResult,
    MaskAsset,
    MediaIntelCache,
    MediaIntelChunk,
    MediaIntelRun,
    MediaIntelWord,
    ReframeKeyframe,
    ReframePlan,
    SpeakerAlias,
)
from app.models.ops import (
    AgentConfig,
    AgentRun,
    AutopilotRun,
    CostEntry,
    Cycle,
    EventLog,
    GpuDevice,
    GpuReservation,
    Job,
    LearningPattern,
    MemoryRecord,
    StorageObject,
    SystemLog,
)
from app.models.performance import (
    CreativeFeature,
    PerformanceObservation,
    RetentionPoint,
)
from app.models.planning import (
    AUTONOMY_MODES,
    BASES,
    PLAN_ITEM_STATUSES,
    EditorialPlan,
    EditorialPlanItem,
    ProductionCapacity,
    TrendSignal,
)
from app.models.timeline import ContentTimeline
from app.models.ugc import UgcProjectRow

__all__ = [
    "Experiment",    "ActiveSpeakerMap",
    "AgentConfig",
    "AgentRun",
    "ApiCredential",
    "AudioTimeMap",
    "AuditLog",
    "AutopilotRun",
    "AvatarOutputRow",
    "AvatarProfileRow",
    "Base",
    "Brand",
    "BrandAsset",
    "BrandDNARow",
    "BrandEffectiveConfig",
    "BrandOverride",
    "BrandPreset",
    "BrowserRun",
    "Campaign",
    "CampaignPlan",
    "CapabilityPermission",
    "Comment",
    "CommunityAction",
    "CommunityInsight",
    "CommunityOpportunity",
    "CommunitySyncState",
    "ContentItem",
    "ContentStatus",
    "ContentTimeline",
    "Conversation",
    "CostEntry",
    "CreativeCommandRow",
    "CreativeFeature",
    "Cycle",
    "DecisionRecordRow",
    "DiarizationSegment",
    "DubbingPlanRow",
    "EditProposal",
    "EventLog",
    "EvidenceRecord",
    "ExportJob",
    "ExportProfile",
    "FaceTrack",
    "FaceTrackSample",
    "GlossaryTerm",
    "GpuDevice",
    "GpuReservation",
    "IntelQCResult",
    "Job",
    "KnowledgeEdge",
    "KnowledgeEvidence",
    "KnowledgeMemory",
    "KnowledgeNode",
    "LearningPattern",
    "LipSyncJob",
    "LocalizationQCReport",
    "LocalizedContent",
    "LongFormChapter",
    "LongFormProject",
    "MaskAsset",
    "MediaAsset",
    "MediaIntelCache",
    "MediaIntelChunk",
    "MediaIntelRun",
    "MediaIntelWord",
    "MemoryRecord",
    "Notification",
    "Opportunity",
    "PerformanceObservation",
    "PlatformVariant",
    "PostMetric",
    "PROJECT_TARGET_TYPES",
    "Project",
    "ProjectArchive",
    "ProjectMember",
    "ProjectTarget",
    "PublishedPost",
    "PublishingJob",
    "PublishingPlan",
    "QualityCheck",
    "ReframeKeyframe",
    "ReframePlan",
    "RefreshToken",
    "RetentionPolicy",
    "RetentionPoint",
    "Review",
    "ReviewAssignment",
    "ReviewDecision",
    "RevisionRequest",
    "ScheduleEntry",
    "Scene",
    "SocialAccount",
    "SocialInteraction",
    "SpeakerAlias",
    "SourceConnector",
    "SourceDocument",
    "StorageObject",
    "SystemLog",
    "TelegramLink",
    "ToolCallAudit",
    "TrendSource",
    "UgcProjectRow",
    "User",
    "Video",
    "VideoVariant",
    "WebhookSubscription",
    "AUTONOMY_MODES",
    "BASES",
    "EditorialPlan",
    "EditorialPlanItem",
    "PLAN_ITEM_STATUSES",
    "ProductionCapacity",
    "TrendSignal",
    "Workspace",
    "WorkspaceApiKey",
    "WorkspaceMember",
    "can_transition",
]
