"""Work 15.5 Port 2: batch material diversity allocation.

The bug these lock down: scene queries were generated by
``kws[i % len(kws)]`` with nothing tracking what had already been used, so a
2-keyword / 8-scene plan emitted 2 distinct queries repeated 4x each, and the
candidate pick for a keyword was the same clip every time. The cut repeats.

The acceptance criteria are the donor's (MoneyPrinterTurbo 1.3.7,
``test/services/test_batch_material_allocation.py``), re-expressed against
YMONEY's shape: a scene plan plus a workspace-scoped usage counter instead of
a download directory plus a task manifest. Each donor invariant names itself.
"""
from __future__ import annotations

import pytest

from app.engine.broll.allocation import (
    REUSE_WARNING_CODE,
    SEQUENTIAL,
    SHORT_WARNING_CODE,
    UNIQUE,
    Clip,
    allocate_batch,
    next_allocation,
    order_clips,
    record_usage,
)
from app.providers import broll as broll_mod
from app.providers.broll import BrollError, SceneVisual


def _clips(spec: list[tuple[str, str]], duration: float = 6.0) -> list[Clip]:
    """``[(source_id, group), ...]`` -> a materialized pool."""
    return [Clip(source_id=sid, group=group, duration=duration) for sid, group in spec]


def _render(ordered: list[Clip], count: int, failing: set[str] | None = None
            ) -> tuple[list[Clip], list[Clip]]:
    """What a renderer does: walk the ordered pool, fill ``count`` slots.

    A clip in ``failing`` is attempted and dies. It consumes no slot (the
    output still needs its footage) and it is not reported as landed, so the
    caller will not commit it to usage.
    """
    bad = failing or set()
    picked: list[Clip] = []
    landed: list[Clip] = []
    for clip in ordered:
        if len(picked) >= count:
            break
        picked.append(clip)
        if clip.source_id not in bad:
            landed.append(clip)
    return picked, landed


# --------------------------------------------------------------------------
# donor invariant: matched batch rotates candidates in keyword order
# (test_matched_batch_rotates_candidates_in_keyword_order)
# --------------------------------------------------------------------------
def test_round_robin_across_keyword_groups_in_keyword_order():
    pool = _clips([(f"room-{i}", "room") for i in range(3)]
                  + [(f"window-{i}", "window") for i in range(3)])
    usage: dict[str, int] = {}
    selections = []
    for index in range(3):
        picked, landed = _render(order_clips(pool, usage), 2)
        selections.append([c.source_id for c in picked])
        usage = record_usage(usage, [c.source_id for c in landed])
    assert selections == [
        ["room-0", "window-0"], ["room-1", "window-1"], ["room-2", "window-2"]]
    # Nothing was spent twice, so nothing is reported as reuse.
    assert set(usage.values()) == {1}


# --------------------------------------------------------------------------
# donor invariant: a batch uses new sources before reuse
# (test_random_batch_uses_new_sources_before_reuse)
# --------------------------------------------------------------------------
def test_new_sources_are_used_before_exhausted_ones():
    pool = _clips([(f"clip-{i}", "room") for i in range(6)], duration=12.0)
    usage: dict[str, int] = {}
    selected: list[str] = []
    for index in range(3):
        picked, landed = _render(order_clips(pool, usage), 2)
        selected.extend(c.source_id for c in picked)
        usage = record_usage(usage, [c.source_id for c in landed])
    assert len(selected) == len(set(selected)) == 6
    assert selected == [f"clip-{i}" for i in range(6)]
    assert max(usage.values()) == 1


def test_already_spent_sources_sort_last():
    pool = _clips([("used", "room"), ("fresh", "room")])
    ordered = [c.source_id for c in order_clips(pool, {"used": 2})]
    assert ordered == ["fresh", "used"]


def test_ties_keep_the_callers_order():
    """Determinism is a product requirement, so the sort must be stable."""
    pool = _clips([("b", "room"), ("a", "room"), ("c", "room")])
    assert [c.source_id for c in order_clips(pool, {})] == ["b", "a", "c"]
    assert [c.source_id for c in order_clips(pool, {"b": 1, "a": 1})] == ["c", "b", "a"]


# --------------------------------------------------------------------------
# donor invariant: shortage reuses only exhausted keyword candidates
# (test_shortage_reuses_only_exhausted_keyword_candidates)
# --------------------------------------------------------------------------
def test_shortage_reuses_only_exhausted_keyword_candidates():
    pool = _clips([("room-0", "room"), ("window", "window"),
                   ("room-1", "room"), ("room-2", "room")])
    usage: dict[str, int] = {}
    selections: list[list[str]] = []
    reuse: list[list[str]] = []
    for index in range(3):
        alloc = next_allocation(pool, usage, index, 2)
        selections.append(alloc.source_ids)
        reuse.append(alloc.reused_sources)
        usage = record_usage(usage, alloc.source_ids)
    assert selections == [
        ["room-0", "window"], ["room-1", "window"], ["room-2", "window"]]
    # Only `window` — the group with a single candidate — was ever exhausted.
    assert reuse == [[], ["window"], ["window"]]
    assert usage == {"room-0": 1, "room-1": 1, "room-2": 1, "window": 3}


def test_shortage_is_reported_not_silently_short():
    batch = allocate_batch(_clips([("only", "room")]), {}, outputs=2, per_output=2)
    assert [out.short_by for out in batch.outputs] == [1, 1]
    # Output 0 cannot fill and has nothing to reuse; output 1 does both.
    assert [w["code"] for w in batch.warnings] == [
        SHORT_WARNING_CODE, REUSE_WARNING_CODE, SHORT_WARNING_CODE]
    assert [w["output_index"] for w in batch.warnings] == [0, 1, 1]


def test_reuse_warning_carries_the_donor_evidence():
    batch = allocate_batch(_clips([("a", "room")]), {}, outputs=2, per_output=1)
    assert batch.warnings == [
        {"code": REUSE_WARNING_CODE, "output_index": 1, "count": 1}]
    assert batch.source_usage == {"a": 2}


def test_a_complete_batch_warns_about_nothing():
    pool = _clips([(f"clip-{i}", "room") for i in range(4)])
    assert allocate_batch(pool, {}, outputs=2, per_output=2).warnings == []


# --------------------------------------------------------------------------
# donor invariant: a failed clip does not count as used
# (test_failed_clip_does_not_count_as_used)
# --------------------------------------------------------------------------
def test_failed_clip_does_not_count_as_used():
    pool = _clips([(f"clip-{i}", "room") for i in range(3)])
    usage: dict[str, int] = {}
    first_alloc = next_allocation(pool, usage, 0, 2)
    assert first_alloc.source_ids == ["clip-0", "clip-1"]
    # clip-0's render died: only the clip that landed is committed, exactly as
    # the donor appends to used_video_paths on success only.
    usage = record_usage(usage, ["clip-1"])
    second = next_allocation(pool, usage, 1, 2)
    assert second.source_ids == ["clip-0", "clip-2"]
    assert second.reused_sources == ["clip-2"] or second.reused_sources == []
    assert usage == {"clip-1": 1}


def test_a_failed_clip_still_leaves_the_slot_to_be_filled():
    """The walk continues past a dead clip instead of costing the output a shot."""
    pool = _clips([(f"clip-{i}", "room") for i in range(3)])
    picked, landed = _render(order_clips(pool, {}), 2, failing={"clip-0"})
    assert [c.source_id for c in picked] == ["clip-0", "clip-1"]
    assert [c.source_id for c in landed] == ["clip-1"]


# --------------------------------------------------------------------------
# donor invariant: unique sources stay ahead of the extra slices of one source
# (test_random_allocation_keeps_unique_sources_ahead_of_extra_slices)
# --------------------------------------------------------------------------
def test_unique_mode_keeps_new_sources_ahead_of_extra_slices():
    pool = [Clip(source_id=name, group="room", duration=3.0)
            for name in ("used", "new") for _ in range(2)]
    ordered = order_clips(pool, {"used": 1}, mode=UNIQUE)
    assert [c.source_id for c in ordered] == ["new", "used", "new", "used"]


def test_unique_mode_takes_the_longest_slice_as_primary():
    """A long recording cut into fragments must contribute its best slice
    first, not a ragged tail fragment."""
    pool = [Clip(source_id="long", group="room", duration=2.0),
            Clip(source_id="long", group="room", duration=9.0),
            Clip(source_id="long", group="room", duration=4.0)]
    ordered = order_clips(pool, {}, mode=UNIQUE)
    assert [c.duration for c in ordered] == [9.0, 2.0, 4.0]


def test_unique_mode_defers_extra_slices_of_every_source():
    pool = [Clip(source_id="a", group="g", duration=5.0),
            Clip(source_id="a", group="g", duration=1.0),
            Clip(source_id="b", group="g", duration=5.0),
            Clip(source_id="b", group="g", duration=1.0)]
    ordered = order_clips(pool, {}, mode=UNIQUE)
    assert [(c.source_id, c.duration) for c in ordered] == [
        ("a", 5.0), ("b", 5.0), ("a", 1.0), ("b", 1.0)]


# --------------------------------------------------------------------------
# donor invariant: a missing manifest falls back to ungrouped allocation
# (test_missing_manifest_falls_back_to_ungrouped_allocation)
# --------------------------------------------------------------------------
def test_ungrouped_clips_still_allocate():
    """No keyword recorded anywhere (no manifest) => flat least-used order."""
    pool = _clips([("a", ""), ("b", ""), ("c", "")])
    ordered = [c.source_id for c in order_clips(pool, {"b": 1})]
    assert ordered == ["a", "c", "b"]


# --------------------------------------------------------------------------
# purity and contract
# --------------------------------------------------------------------------
def test_allocation_does_not_mutate_its_inputs():
    pool = _clips([("b", "room"), ("a", "room"), ("c", "room")])
    before = [(c.source_id, c.group) for c in pool]
    usage = {"b": 1}
    snapshot = dict(usage)
    order_clips(pool, usage)
    allocate_batch(pool, usage, outputs=2, per_output=1)
    next_allocation(pool, usage, 0, 2)
    record_usage(usage, ["z"])
    assert [(c.source_id, c.group) for c in pool] == before
    assert usage == snapshot


def test_record_usage_returns_a_new_counter():
    usage = {"a": 1}
    updated = record_usage(usage, ["a", "b", "", None])
    assert updated == {"a": 2, "b": 1}
    assert usage == {"a": 1}


def test_empty_inputs_are_empty_results():
    assert order_clips([], {}) == []
    assert order_clips(None, None) == []
    assert next_allocation([], {}, 0, 3).allocations == ()
    assert allocate_batch([], {}, outputs=2, per_output=2).outputs[0].clips == []


def test_unknown_mode_is_refused_rather_than_guessed():
    with pytest.raises(ValueError, match="unknown allocation mode"):
        order_clips(_clips([("a", "g")]), {}, mode="shuffle")


def test_allocation_module_performs_no_io():
    import inspect

    from app.engine.broll import allocation as mod

    assert "httpx" not in inspect.getsource(mod)
    assert "session" not in inspect.getsource(mod)


def test_mode_defaults_to_sequential():
    assert SEQUENTIAL == "sequential"
    pool = _clips([("a", "one"), ("b", "two")])
    assert order_clips(pool, {}) == order_clips(pool, {}, mode=SEQUENTIAL)


# --------------------------------------------------------------------------
# the wire-in: plan_scenes -> select_stock_clips
# --------------------------------------------------------------------------
def _no_llm(monkeypatch):
    monkeypatch.setattr("app.providers.llm.llm_available", lambda: False)


def _catalog(count: int, *, group: str = "cand", width: int = 1080,
             height: int = 1920, duration: float = 6.0) -> list:
    from app.engine.broll.aspect import orientation_of
    from app.providers.broll import StockCandidate

    return [StockCandidate(video_id=f"{group}-{i}", preview=f"p{i}", duration=duration,
                           author="a", page_url="u", width=width, height=height,
                           orientation=orientation_of(width, height))
            for i in range(count)]


def test_plan_attaches_the_keyword_that_drives_allocation(monkeypatch):
    _no_llm(monkeypatch)
    plan = broll_mod.plan_scenes("save money", ["budget", "coins"], 4, "ws-alloc")
    assert [s.keyword for s in plan] == ["budget", "budget", "coins", "coins"]
    assert all(isinstance(s.performance_json, dict) for s in plan)


def test_both_lanes_see_every_keyword(monkeypatch):
    """The lane-blind rotation this replaces: with 2 keywords and 8 scenes the
    stock lane searched `budget` four times and `coins` never, and the AI lane
    was the mirror image. Rotation is per lane now, so each lane spans the set.
    """
    _no_llm(monkeypatch)
    plan = broll_mod.plan_scenes("save money", ["budget", "coins"], 8, "ws-alloc")
    stock = [s.keyword for s in plan if s.source == "stock"]
    ai = [s.keyword for s in plan if s.source == "ai"]
    assert stock == ["budget", "coins", "budget", "coins"]
    assert ai == ["budget", "coins", "budget", "coins"]
    # ... and the queries are distinct rather than two strings repeated 4x.
    assert len({s.query for s in plan}) == 2  # only two terms exist to write


def test_single_keyword_plan_is_unchanged(monkeypatch):
    _no_llm(monkeypatch)
    plan = broll_mod.plan_scenes("save money", ["budget"], 4, "ws-alloc")
    assert [s.keyword for s in plan] == ["budget"] * 4
    assert [s.source for s in plan] == ["stock", "ai", "stock", "ai"]


def test_four_scenes_on_one_keyword_get_four_different_clips(tmp_path, monkeypatch):
    """The live bug: one keyword, four stock scenes, one clip repeated 4x."""
    _no_llm(monkeypatch)
    monkeypatch.chdir(tmp_path)
    plan = broll_mod.plan_scenes("save money", ["budget"], 8, "ws-alloc")
    stock = [s for s in plan if s.source == "stock"]
    assert len(stock) == 4
    monkeypatch.setattr(broll_mod, "search_stock",
                        lambda q, per_page=4, orientation="portrait": _catalog(per_page))
    monkeypatch.setattr(broll_mod, "fetch_stock_clip",
                        lambda vid, ws, aspect="9:16": f"data/videos/{ws}/broll/{vid}.mp4")
    resolved = broll_mod.select_stock_clips(plan, "ws-alloc", source_usage={})
    used = [s for s in resolved if s.source == "stock"]
    assert [s.performance_json["material"]["clip_id"] for s in used] == [
        "cand-0", "cand-1", "cand-2", "cand-3"]
    assert all(s.performance_json["material"]["reused"] is False for s in used)
    assert all("material_reuse" not in s.performance_json for s in used)


def test_reuse_is_reported_on_the_scene_not_hidden(tmp_path, monkeypatch):
    """One candidate, four scenes: three of them must say so."""
    _no_llm(monkeypatch)
    monkeypatch.chdir(tmp_path)
    plan = broll_mod.plan_scenes("save money", ["budget"], 8, "ws-alloc")
    monkeypatch.setattr(broll_mod, "search_stock",
                        lambda q, per_page=4, orientation="portrait": _catalog(1))
    monkeypatch.setattr(broll_mod, "fetch_stock_clip",
                        lambda vid, ws, aspect="9:16": f"data/videos/{ws}/broll/{vid}.mp4")
    resolved = broll_mod.select_stock_clips(plan, "ws-alloc", source_usage={})
    perf = [s.performance_json for s in resolved if s.source == "stock"]
    assert [p["material"]["uses_before"] for p in perf] == [0, 1, 2, 3]
    assert [p["material"]["reused"] for p in perf] == [False, True, True, True]
    assert perf[0].get("material_reuse") is None
    assert perf[1]["material_reuse"] == {
        "code": REUSE_WARNING_CODE, "source_id": "cand-0", "uses_before": 1}


def test_performance_json_key_matches_the_scene_column(tmp_path, monkeypatch):
    """The report has to land in a real column, not a field we invented."""
    from app.models.assets import Scene

    assert "performance_json" in Scene.__table__.columns
    assert isinstance(Scene.__table__.columns["performance_json"].type, type(
        Scene.__table__.columns["assets_json"].type))
    _no_llm(monkeypatch)
    monkeypatch.chdir(tmp_path)
    plan = broll_mod.plan_scenes("save money", ["budget"], 2, "ws-alloc")
    monkeypatch.setattr(broll_mod, "search_stock",
                        lambda q, per_page=4, orientation="portrait": _catalog(2))
    monkeypatch.setattr(broll_mod, "fetch_stock_clip",
                        lambda vid, ws, aspect="9:16": f"data/videos/{ws}/broll/{vid}.mp4")
    resolved = broll_mod.select_stock_clips(plan, "ws-alloc", source_usage={})
    # scene_sync persists this dict verbatim, so it must be JSON-shaped.
    import json

    payload = resolved[0].performance_json
    assert json.loads(json.dumps(payload)) == payload
    assert set(payload) <= {"material", "material_reuse", "material_short"}


def test_input_plan_is_not_mutated(tmp_path, monkeypatch):
    _no_llm(monkeypatch)
    monkeypatch.chdir(tmp_path)
    plan = broll_mod.plan_scenes("save money", ["budget"], 4, "ws-alloc")
    before = [(s.index, dict(s.performance_json)) for s in plan]
    monkeypatch.setattr(broll_mod, "search_stock",
                        lambda q, per_page=4, orientation="portrait": _catalog(2))
    monkeypatch.setattr(broll_mod, "fetch_stock_clip",
                        lambda vid, ws, aspect="9:16": f"data/videos/{ws}/broll/{vid}.mp4")
    broll_mod.select_stock_clips(plan, "ws-alloc", source_usage={})
    assert [(s.index, dict(s.performance_json)) for s in plan] == before


def test_a_failed_fetch_does_not_spend_the_source(tmp_path, monkeypatch):
    """The donor's failure invariant, through the real selection path.

    cand-0 dies on its first download, exactly like the donor's one-shot
    ``OSError``. The scene walks past it to cand-1, and because the failure was
    never committed, the next scene is offered cand-0 again with a fresh
    ``uses_before`` of 0.
    """
    _no_llm(monkeypatch)
    monkeypatch.chdir(tmp_path)
    plan = broll_mod.plan_scenes("save money", ["budget"], 8, "ws-alloc")
    attempts: list[str] = []

    def flaky(vid, ws, aspect="9:16"):
        attempts.append(vid)
        if vid == "cand-0" and len(attempts) == 1:
            raise BrollError("clip download failed")
        return f"data/videos/{ws}/broll/{vid}.mp4"

    monkeypatch.setattr(broll_mod, "search_stock",
                        lambda q, per_page=4, orientation="portrait": _catalog(2))
    monkeypatch.setattr(broll_mod, "fetch_stock_clip", flaky)
    resolved = broll_mod.select_stock_clips(plan, "ws-alloc", source_usage={})
    used = [s for s in resolved if s.source == "stock"]
    # cand-1 (the survivor) then cand-0, cand-0, then cand-1 again — the tail
    # re-uses cand-1 because it is the least spent of the two, which is the
    # point: reuse is the fallback, not the first choice.
    assert [s.performance_json["material"]["clip_id"] for s in used] == [
        "cand-1", "cand-0", "cand-0", "cand-1"]
    # The proof: cand-0's first (failed) use left no trace in the counter.
    assert used[1].performance_json["material"]["uses_before"] == 0
    assert used[1].performance_json["material"]["reused"] is False
    assert attempts[0] == "cand-0" and attempts[1] == "cand-1"


def test_a_permanently_dead_clip_leaves_the_scene_reported_short(tmp_path, monkeypatch):
    """Never served the wrong clip, never counted as used, never silent."""
    _no_llm(monkeypatch)
    monkeypatch.chdir(tmp_path)
    plan = broll_mod.plan_scenes("save money", ["budget"], 2, "ws-alloc")

    def dead(vid, ws, aspect="9:16"):
        raise BrollError("clip download failed")

    monkeypatch.setattr(broll_mod, "search_stock",
                        lambda q, per_page=4, orientation="portrait": _catalog(1))
    monkeypatch.setattr(broll_mod, "fetch_stock_clip", dead)
    resolved = broll_mod.select_stock_clips(plan, "ws-alloc", source_usage={})
    perf = resolved[0].performance_json
    assert perf["material_short"]["code"] == SHORT_WARNING_CODE
    assert broll_mod.load_source_usage("ws-alloc") == {}


def test_scene_with_no_usable_clip_is_reported_short(tmp_path, monkeypatch):
    _no_llm(monkeypatch)
    monkeypatch.chdir(tmp_path)
    plan = broll_mod.plan_scenes("save money", ["budget"], 2, "ws-alloc")
    monkeypatch.setattr(broll_mod, "search_stock", lambda *a, **k: [])
    resolved = broll_mod.select_stock_clips(plan, "ws-alloc", source_usage={})
    perf = resolved[0].performance_json
    assert perf["material_short"]["code"] == SHORT_WARNING_CODE


def test_search_failure_is_reported_per_group_and_never_raises(tmp_path, monkeypatch):
    """One dead keyword must not kill the plan, and one keyword is searched
    once — not once per scene."""
    _no_llm(monkeypatch)
    monkeypatch.chdir(tmp_path)
    plan = broll_mod.plan_scenes("save money", ["budget", "coins"], 4, "ws-alloc")
    calls: list[str] = []

    def flaky(query, per_page=4, orientation="portrait"):
        calls.append(query)
        if "budget" in query:
            raise BrollError("Pexels key not configured")
        return _catalog(2, group="coins")

    monkeypatch.setattr(broll_mod, "search_stock", flaky)
    monkeypatch.setattr(broll_mod, "fetch_stock_clip",
                        lambda vid, ws, aspect="9:16": f"data/videos/{ws}/broll/{vid}.mp4")
    resolved = broll_mod.select_stock_clips(plan, "ws-alloc", source_usage={})
    assert calls == ["save money budget", "save money coins"]
    by_index = {s.index: s for s in resolved}
    assert by_index[0].performance_json["material_short"]["code"] == SHORT_WARNING_CODE
    assert by_index[2].performance_json["material"]["clip_id"] == "coins-0"
    # The AI scenes were never touched by the stock lane.
    assert by_index[1].performance_json == {} and by_index[3].performance_json == {}


def test_ai_scenes_pass_through_untouched(tmp_path, monkeypatch):
    _no_llm(monkeypatch)
    monkeypatch.chdir(tmp_path)
    plan = [SceneVisual(0, "q0", "p0", "ai"), SceneVisual(1, "q1", "p1", "ai")]
    monkeypatch.setattr(broll_mod, "search_stock",
                        lambda *a, **k: pytest.fail("AI scenes must not search stock"))
    resolved = broll_mod.select_stock_clips(plan, "ws-alloc", source_usage={})
    assert resolved == plan
    assert all(s.performance_json == {} for s in resolved)


def test_orientation_gate_applies_to_the_candidate_pool(tmp_path, monkeypatch):
    """Landscape hits never enter a 9:16 pool while a vertical hit exists."""
    _no_llm(monkeypatch)
    monkeypatch.chdir(tmp_path)
    from app.engine.broll.aspect import orientation_of

    plan = broll_mod.plan_scenes("save money", ["budget"], 8, "ws-alloc")
    mixed = _catalog(2, group="land", width=1920, height=1080)
    mixed[0].orientation = orientation_of(1920, 1080)
    mixed[1].orientation = orientation_of(1920, 1080)
    vertical = _catalog(2, group="vert")
    monkeypatch.setattr(broll_mod, "search_stock",
                        lambda q, per_page=4, orientation="portrait": mixed + vertical)
    monkeypatch.setattr(broll_mod, "fetch_stock_clip",
                        lambda vid, ws, aspect="9:16": f"data/videos/{ws}/broll/{vid}.mp4")
    resolved = broll_mod.select_stock_clips(plan, "ws-alloc", source_usage={})
    picked = [s.performance_json["material"]["clip_id"]
              for s in resolved if s.source == "stock"]
    assert set(picked) == {"vert-0", "vert-1"}


# --------------------------------------------------------------------------
# workspace isolation
# --------------------------------------------------------------------------
def test_usage_lives_inside_the_workspace_directory(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    path = broll_mod.usage_store_path("ws-one")
    assert path.parts[-3:] == ("ws-one", "broll", "material_usage.json")
    assert "ws-two" not in str(path)


def test_usage_round_trips_and_never_leaks_between_workspaces(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    broll_mod.save_source_usage("ws-one", {"a": 2})
    assert broll_mod.load_source_usage("ws-one") == {"a": 2}
    assert broll_mod.load_source_usage("ws-two") == {}


def test_a_corrupt_counter_reads_as_zero_usage(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    path = broll_mod.usage_store_path("ws-one")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("{not json", encoding="utf-8")
    assert broll_mod.load_source_usage("ws-one") == {}
    path.write_text('["a", 1]', encoding="utf-8")
    assert broll_mod.load_source_usage("ws-one") == {}


def test_wired_selection_persists_usage_per_workspace(tmp_path, monkeypatch):
    _no_llm(monkeypatch)
    monkeypatch.chdir(tmp_path)
    plan = broll_mod.plan_scenes("save money", ["budget"], 8, "ws-one")
    monkeypatch.setattr(broll_mod, "search_stock",
                        lambda q, per_page=4, orientation="portrait": _catalog(2))
    monkeypatch.setattr(broll_mod, "fetch_stock_clip",
                        lambda vid, ws, aspect="9:16": f"data/videos/{ws}/broll/{vid}.mp4")
    broll_mod.select_stock_clips(plan, "ws-one", source_usage={})
    assert broll_mod.load_source_usage("ws-one") == {"cand-0": 2, "cand-1": 2}
    assert broll_mod.load_source_usage("ws-two") == {}


def test_scene_visual_keeps_its_field_order_for_callers():
    """Existing positional construction of SceneVisual must keep working."""
    scene = SceneVisual(0, "q", "p", "stock")
    assert (scene.index, scene.query, scene.prompt, scene.source) == (0, "q", "p", "stock")
    assert scene.keyword == "" and scene.performance_json == {}


def test_performance_json_defaults_are_not_shared():
    a, b = SceneVisual(0, "q", "p", "stock"), SceneVisual(1, "q", "p", "stock")
    a.performance_json["material"] = {"x": 1}
    assert b.performance_json == {}
